POST http://localhost:8099/api/v1/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "12345678"
}

###

GET http://localhost:8099/api/v1/organizations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGUiOlsiU1VQRVJfQURNSU4iXSwiaWF0IjoxNjc2ODkxMTI4LCJleHAiOjE2NzY5Nzc1Mjh9.ev-4TtNCxmAeqbxEPAhkQR5qvxhrYfJmCkTBIqBanLE

###

POST http://localhost:8099/api/v1/organizations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGUiOlsiU1VQRVJfQURNSU4iXSwiaWF0IjoxNjc2ODkxMTI4LCJleHAiOjE2NzY5Nzc1Mjh9.ev-4TtNCxmAeqbxEPAhkQR5qvxhrYfJmCkTBIqBanLE

{
  "shortName": "ОСФР по Архангельской области и НАО",
  "fullName": "Государственное учреждение - Отделение социального фонда России по Архангельской области и Ненецкому автономному округу",
  "inn": 2911003480
}

###

PUT http://localhost:8099/api/v1/organizations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGUiOlsiU1VQRVJfQURNSU4iXSwiaWF0IjoxNjc2ODkxMTI4LCJleHAiOjE2NzY5Nzc1Mjh9.ev-4TtNCxmAeqbxEPAhkQR5qvxhrYfJmCkTBIqBanLE

{
  "id": 1,
  "shortName": "ОСФР по Архангельской области и НАО",
  "fullName": "ГУ - Отделение социального фонда России по Архангельской области и Ненецкому автономному округу",
  "inn": 2911003480
}
###

DELETE http://localhost:8099/api/v1/organizations/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGUiOlsiU1VQRVJfQURNSU4iXSwiaWF0IjoxNjc2ODkxMTI4LCJleHAiOjE2NzY5Nzc1Mjh9.ev-4TtNCxmAeqbxEPAhkQR5qvxhrYfJmCkTBIqBanLE

###
