server:
  port: ${SERVER_PORT:8098}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3307}/${DB_NAME:mz_v1}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:12345678}
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
  servlet:
    multipart:
      max-file-size: 10000000
      max-request-size: 10000000
  main:
    banner-mode: off

security:
  ldap:
    domain: ${DOMAIN_NAME:domain}
    username: ${DOMAIN_USERNAME:username}
    password: ${DOMAIN_USER_PASSWORD:password}
  secret: ${SECRET_KEY:1 kure sluga userdnyi boga}
  authorization:
    header: Authorization
    expiration: 86400
  user:
    username: ${DEFAULT_USERNAME:admin}
    password: ${DEFAULT_PASSWORD:12345678}
    role: ${DEFAULT_ROLE:SUPER_ADMIN}
    email: ${DEFAULT_EMAIL:admin@mail.com}
  front:
    host: http://${FRONT_HOST:*}:${FRONT_PORT:*}

setup:
  page:
    current: 0
    size: 10

management:
  endpoints:
    web:
      exposure:
        include: "health,info,flyway,env"
      base-path: /monitor
springdoc:
  swagger-ui:
    path: /api-docs/swagger-ui-custom.html
  api-docs:
    path: /api-docs